2024-03-23T08:39:36.161619959Z    _____                               
2024-03-23T08:39:36.161650959Z   /  _  \ __________ _________   ____  
2024-03-23T08:39:36.161654959Z  /  /_\  \\___   /  |  \_  __ \_/ __ \ 
2024-03-23T08:39:36.161658159Z /    |    \/    /|  |  /|  | \/\  ___/ 
2024-03-23T08:39:36.161661159Z \____|__  /_____ \____/ |__|    \___  >
2024-03-23T08:39:36.161664359Z         \/      \/                  \/ 
2024-03-23T08:39:36.161667259Z A P P   S E R V I C E   O N   L I N U X
2024-03-23T08:39:36.161670059Z 
2024-03-23T08:39:36.161672759Z Documentation: http://aka.ms/webapp-linux
2024-03-23T08:39:36.161675359Z Python 3.11.7
2024-03-23T08:39:36.161678159Z Note: Any data outside '/home' is not persisted
2024-03-23T08:39:39.787465004Z Starting OpenBSD Secure Shell server: sshd.
2024-03-23T08:39:39.987531361Z App Command Line not configured, will attempt auto-detect
2024-03-23T08:39:39.987555961Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite
2024-03-23T08:39:40.256743936Z Found build manifest file at '/home/site/wwwroot/oryx-manifest.toml'. Deserializing it...
2024-03-23T08:39:40.279767242Z Build Operation ID: 75ef9913c02ffce1
2024-03-23T08:39:40.289974977Z Output is compressed. Extracting it...
2024-03-23T08:39:40.290007178Z Oryx Version: 0.2.20240127.1, Commit: 4b7f2dffcc69c214f9806d67a85ec8926e2393e1, ReleaseTagName: 20240127.1
2024-03-23T08:39:40.298255387Z Extracting '/home/site/wwwroot/output.tar.gz' to directory '/tmp/8dc4a5f33ada8c2'...
2024-03-23T08:40:09.137624972Z App path is set to '/tmp/8dc4a5f33ada8c2'
2024-03-23T08:40:09.151739659Z Detected an app based on Flask
2024-03-23T08:40:09.151754059Z Generating `gunicorn` command for 'app:app'
2024-03-23T08:40:09.151729359Z Writing output script to '/opt/startup/startup.sh'
2024-03-23T08:40:09.278581842Z Using packages from virtual environment antenv located at /tmp/8dc4a5f33ada8c2/antenv.
2024-03-23T08:40:09.278614342Z Updated PYTHONPATH to '/opt/startup/app_logs:/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages'
2024-03-23T08:40:10.443818805Z [2024-03-23 08:40:10 +0000] [73] [INFO] Starting gunicorn 21.2.0
2024-03-23T08:40:10.521932241Z [2024-03-23 08:40:10 +0000] [73] [INFO] Listening at: http://0.0.0.0:8000 (73)
2024-03-23T08:40:10.523207358Z [2024-03-23 08:40:10 +0000] [73] [INFO] Using worker: sync
2024-03-23T08:40:10.535759925Z [2024-03-23 08:40:10 +0000] [76] [INFO] Booting worker with pid: 76
2024-03-23T08:40:20.521158038Z [2024-03-23 08:40:20 +0000] [76] [ERROR] Exception in worker process
2024-03-23T08:40:20.521194839Z Traceback (most recent call last):
2024-03-23T08:40:20.521199239Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2024-03-23T08:40:20.521214239Z     worker.init_process()
2024-03-23T08:40:20.521217539Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
2024-03-23T08:40:20.521220839Z     self.load_wsgi()
2024-03-23T08:40:20.521223739Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2024-03-23T08:40:20.521227139Z     self.wsgi = self.app.wsgi()
2024-03-23T08:40:20.521230139Z                 ^^^^^^^^^^^^^^^
2024-03-23T08:40:20.521233239Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-03-23T08:40:20.521236339Z     self.callable = self.load()
2024-03-23T08:40:20.521239239Z                     ^^^^^^^^^^^
2024-03-23T08:40:20.521242140Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2024-03-23T08:40:20.521245440Z     return self.load_wsgiapp()
2024-03-23T08:40:20.521248240Z            ^^^^^^^^^^^^^^^^^^^
2024-03-23T08:40:20.521251440Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2024-03-23T08:40:20.521254740Z     return util.import_app(self.app_uri)
2024-03-23T08:40:20.521257940Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23T08:40:20.521260840Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
2024-03-23T08:40:20.521264040Z     mod = importlib.import_module(module)
2024-03-23T08:40:20.521267040Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23T08:40:20.521270140Z   File "/opt/python/3.11.7/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-03-23T08:40:20.521273240Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-03-23T08:40:20.521276440Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23T08:40:20.521279540Z   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-03-23T08:40:20.521283140Z   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-03-23T08:40:20.521286340Z   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-03-23T08:40:20.521291040Z   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-03-23T08:40:20.521294140Z   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-03-23T08:40:20.521297340Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-03-23T08:40:20.521300540Z   File "/tmp/8dc4a5f33ada8c2/app.py", line 10, in <module>
2024-03-23T08:40:20.521309940Z     from applicationinsights.flask.ext import AppInsights
2024-03-23T08:40:20.521313140Z ModuleNotFoundError: No module named 'applicationinsights'
2024-03-23T08:40:20.521316240Z [2024-03-23 08:40:20 +0000] [76] [INFO] Worker exiting (pid: 76)
2024-03-23T08:40:21.246125431Z [2024-03-23 08:40:21 +0000] [73] [ERROR] Worker (pid:76) exited with code 3
2024-03-23T08:40:21.283674027Z [2024-03-23 08:40:21 +0000] [73] [ERROR] Shutting down: Master
2024-03-23T08:40:21.283700728Z [2024-03-23 08:40:21 +0000] [73] [ERROR] Reason: Worker failed to boot.

2024-03-23T13:19:11.034556227Z    _____                               
2024-03-23T13:19:11.034587927Z   /  _  \ __________ _________   ____  
2024-03-23T13:19:11.034592027Z  /  /_\  \\___   /  |  \_  __ \_/ __ \ 
2024-03-23T13:19:11.034595427Z /    |    \/    /|  |  /|  | \/\  ___/ 
2024-03-23T13:19:11.034598327Z \____|__  /_____ \____/ |__|    \___  >
2024-03-23T13:19:11.034601327Z         \/      \/                  \/ 
2024-03-23T13:19:11.034604227Z A P P   S E R V I C E   O N   L I N U X
2024-03-23T13:19:11.034607027Z 
2024-03-23T13:19:11.034610027Z Documentation: http://aka.ms/webapp-linux
2024-03-23T13:19:11.034613227Z Python 3.11.7
2024-03-23T13:19:11.034615927Z Note: Any data outside '/home' is not persisted
2024-03-23T13:19:14.734891748Z Starting OpenBSD Secure Shell server: sshd.
2024-03-23T13:19:15.007228463Z App Command Line not configured, will attempt auto-detect
2024-03-23T13:19:15.026029112Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite
2024-03-23T13:19:15.538258533Z Found build manifest file at '/home/site/wwwroot/oryx-manifest.toml'. Deserializing it...
2024-03-23T13:19:15.538294034Z Build Operation ID: 75ef9913c02ffce1
2024-03-23T13:19:15.538298834Z Oryx Version: 0.2.20240127.1, Commit: 4b7f2dffcc69c214f9806d67a85ec8926e2393e1, ReleaseTagName: 20240127.1
2024-03-23T13:19:15.538312634Z Output is compressed. Extracting it...
2024-03-23T13:19:15.538316034Z Extracting '/home/site/wwwroot/output.tar.gz' to directory '/tmp/8dc4a5f33ada8c2'...
2024-03-23T13:19:37.668130747Z Writing output script to '/opt/startup/startup.sh'
2024-03-23T13:19:37.668400851Z App path is set to '/tmp/8dc4a5f33ada8c2'
2024-03-23T13:19:37.668410151Z Detected an app based on Flask
2024-03-23T13:19:37.668413651Z Generating `gunicorn` command for 'app:app'
2024-03-23T13:19:37.858498749Z Using packages from virtual environment antenv located at /tmp/8dc4a5f33ada8c2/antenv.
2024-03-23T13:19:37.858536549Z Updated PYTHONPATH to '/opt/startup/app_logs:/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages'
2024-03-23T13:19:39.186132496Z [2024-03-23 13:19:39 +0000] [70] [INFO] Starting gunicorn 21.2.0
2024-03-23T13:19:39.214665171Z [2024-03-23 13:19:39 +0000] [70] [INFO] Listening at: http://0.0.0.0:8000 (70)
2024-03-23T13:19:39.216367793Z [2024-03-23 13:19:39 +0000] [70] [INFO] Using worker: sync
2024-03-23T13:19:39.236122553Z [2024-03-23 13:19:39 +0000] [73] [INFO] Booting worker with pid: 73
2024-03-23T13:19:49.988165554Z [2024-03-23 13:19:49 +0000] [73] [ERROR] Exception in worker process
2024-03-23T13:19:49.988202955Z Traceback (most recent call last):
2024-03-23T13:19:49.988207655Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2024-03-23T13:19:49.988225855Z     worker.init_process()
2024-03-23T13:19:49.988235055Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
2024-03-23T13:19:49.988238455Z     self.load_wsgi()
2024-03-23T13:19:49.988241556Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2024-03-23T13:19:49.988244956Z     self.wsgi = self.app.wsgi()
2024-03-23T13:19:49.988247956Z                 ^^^^^^^^^^^^^^^
2024-03-23T13:19:49.988250856Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-03-23T13:19:49.988253956Z     self.callable = self.load()
2024-03-23T13:19:49.988256956Z                     ^^^^^^^^^^^
2024-03-23T13:19:49.988259756Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2024-03-23T13:19:49.988263056Z     return self.load_wsgiapp()
2024-03-23T13:19:49.988266056Z            ^^^^^^^^^^^^^^^^^^^
2024-03-23T13:19:49.988269056Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2024-03-23T13:19:49.988272156Z     return util.import_app(self.app_uri)
2024-03-23T13:19:49.988275056Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23T13:19:49.988277956Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
2024-03-23T13:19:49.988281156Z     mod = importlib.import_module(module)
2024-03-23T13:19:49.988284056Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23T13:19:49.988287056Z   File "/opt/python/3.11.7/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-03-23T13:19:49.988290756Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-03-23T13:19:49.988294156Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23T13:19:49.988297156Z   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-03-23T13:19:49.988300756Z   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-03-23T13:19:49.988303756Z   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-03-23T13:19:49.988306856Z   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-03-23T13:19:49.988309856Z   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-03-23T13:19:49.988313257Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-03-23T13:19:49.988316457Z   File "/tmp/8dc4a5f33ada8c2/app.py", line 10, in <module>
2024-03-23T13:19:49.988320557Z     from applicationinsights.flask.ext import AppInsights
2024-03-23T13:19:49.988323657Z ModuleNotFoundError: No module named 'applicationinsights'
2024-03-23T13:19:49.998678999Z [2024-03-23 13:19:49 +0000] [73] [INFO] Worker exiting (pid: 73)
2024-03-23T13:19:50.884083158Z [2024-03-23 13:19:50 +0000] [70] [ERROR] Worker (pid:73) exited with code 3
2024-03-23T13:19:50.893654890Z [2024-03-23 13:19:50 +0000] [70] [ERROR] Shutting down: Master
2024-03-23T13:19:50.894165897Z [2024-03-23 13:19:50 +0000] [70] [ERROR] Reason: Worker failed to boot.

2024-03-23T13:31:57.519157618Z    _____                               
2024-03-23T13:31:57.519192219Z   /  _  \ __________ _________   ____  
2024-03-23T13:31:57.519196119Z  /  /_\  \\___   /  |  \_  __ \_/ __ \ 
2024-03-23T13:31:57.519199119Z /    |    \/    /|  |  /|  | \/\  ___/ 
2024-03-23T13:31:57.519202019Z \____|__  /_____ \____/ |__|    \___  >
2024-03-23T13:31:57.519205119Z         \/      \/                  \/ 
2024-03-23T13:31:57.519208019Z A P P   S E R V I C E   O N   L I N U X
2024-03-23T13:31:57.519210819Z 
2024-03-23T13:31:57.519213419Z Documentation: http://aka.ms/webapp-linux
2024-03-23T13:31:57.519216419Z Python 3.11.7
2024-03-23T13:31:57.519219219Z Note: Any data outside '/home' is not persisted
2024-03-23T13:32:01.766921856Z Starting OpenBSD Secure Shell server: sshd.
2024-03-23T13:32:02.179565891Z App Command Line not configured, will attempt auto-detect
2024-03-23T13:32:02.179590892Z Launching oryx with: create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -virtualEnvName antenv -defaultApp /opt/defaultsite
2024-03-23T13:32:02.831671255Z Found build manifest file at '/home/site/wwwroot/oryx-manifest.toml'. Deserializing it...
2024-03-23T13:32:02.850334814Z Build Operation ID: 75ef9913c02ffce1
2024-03-23T13:32:02.870747298Z Oryx Version: 0.2.20240127.1, Commit: 4b7f2dffcc69c214f9806d67a85ec8926e2393e1, ReleaseTagName: 20240127.1
2024-03-23T13:32:02.882492361Z Output is compressed. Extracting it...
2024-03-23T13:32:02.902679641Z Extracting '/home/site/wwwroot/output.tar.gz' to directory '/tmp/8dc4a5f33ada8c2'...
2024-03-23T13:32:34.869733512Z App path is set to '/tmp/8dc4a5f33ada8c2'
2024-03-23T13:32:34.956862063Z Detected an app based on Flask
2024-03-23T13:32:34.957360769Z Generating `gunicorn` command for 'app:app'
2024-03-23T13:32:34.959777801Z Writing output script to '/opt/startup/startup.sh'
2024-03-23T13:32:35.071510677Z Using packages from virtual environment antenv located at /tmp/8dc4a5f33ada8c2/antenv.
2024-03-23T13:32:35.071543278Z Updated PYTHONPATH to '/opt/startup/app_logs:/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages'
2024-03-23T13:32:36.497801316Z [2024-03-23 13:32:36 +0000] [76] [INFO] Starting gunicorn 21.2.0
2024-03-23T13:32:36.528730525Z [2024-03-23 13:32:36 +0000] [76] [INFO] Listening at: http://0.0.0.0:8000 (76)
2024-03-23T13:32:36.529665537Z [2024-03-23 13:32:36 +0000] [76] [INFO] Using worker: sync
2024-03-23T13:32:36.546305457Z [2024-03-23 13:32:36 +0000] [79] [INFO] Booting worker with pid: 79
2024-03-23T13:32:49.339078626Z [2024-03-23 13:32:49 +0000] [79] [ERROR] Exception in worker process
2024-03-23T13:32:49.339113726Z Traceback (most recent call last):
2024-03-23T13:32:49.339118527Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
2024-03-23T13:32:49.339135427Z     worker.init_process()
2024-03-23T13:32:49.339144827Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
2024-03-23T13:32:49.339148327Z     self.load_wsgi()
2024-03-23T13:32:49.339151227Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2024-03-23T13:32:49.339154727Z     self.wsgi = self.app.wsgi()
2024-03-23T13:32:49.339157627Z                 ^^^^^^^^^^^^^^^
2024-03-23T13:32:49.339160427Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-03-23T13:32:49.339163627Z     self.callable = self.load()
2024-03-23T13:32:49.339166827Z                     ^^^^^^^^^^^
2024-03-23T13:32:49.339169827Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2024-03-23T13:32:49.339172927Z     return self.load_wsgiapp()
2024-03-23T13:32:49.339175827Z            ^^^^^^^^^^^^^^^^^^^
2024-03-23T13:32:49.339178827Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2024-03-23T13:32:49.339181927Z     return util.import_app(self.app_uri)
2024-03-23T13:32:49.339184827Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23T13:32:49.339187827Z   File "/tmp/8dc4a5f33ada8c2/antenv/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
2024-03-23T13:32:49.339191028Z     mod = importlib.import_module(module)
2024-03-23T13:32:49.339194328Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23T13:32:49.339637433Z   File "/opt/python/3.11.7/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-03-23T13:32:49.339643233Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-03-23T13:32:49.339646534Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-23T13:32:49.339649634Z   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-03-23T13:32:49.339653034Z   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-03-23T13:32:49.339656034Z   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-03-23T13:32:49.339659334Z   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-03-23T13:32:49.339662434Z   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-03-23T13:32:49.339665534Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-03-23T13:32:49.339668634Z   File "/tmp/8dc4a5f33ada8c2/app.py", line 10, in <module>
2024-03-23T13:32:49.339673934Z     from applicationinsights.flask.ext import AppInsights
2024-03-23T13:32:49.339677034Z ModuleNotFoundError: No module named 'applicationinsights'
2024-03-23T13:32:49.378470545Z [2024-03-23 13:32:49 +0000] [79] [INFO] Worker exiting (pid: 79)
2024-03-23T13:32:50.363210418Z [2024-03-23 13:32:50 +0000] [76] [ERROR] Worker (pid:79) exited with code 3
2024-03-23T13:32:50.441615151Z [2024-03-23 13:32:50 +0000] [76] [ERROR] Shutting down: Master
2024-03-23T13:32:50.441651751Z [2024-03-23 13:32:50 +0000] [76] [ERROR] Reason: Worker failed to boot.

